spring:
  mail:
    host: smtp.163.com #发送邮件服务器m
    #username: 15233088662@163.com #发送邮件的邮箱地址
    username: jrbyposttest@163.com
    #password: YJTWHVSWPMHTVDKQ #客户端授权码，不是邮箱密码,网易的是自己设置的
    password: RBRGRIGFOJNGTOHO
    properties.mail.smtp.port: 994 #465或者994
    from: jrbyposttest@163.com # 发送邮件的地址，和上面username一致
    nickname: 东软教育
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
sms:
  aliyun:
    accessKeyID: LTAI4GDr1DAsYncMPsk9Db59 # accessKeyID
    accessKeySecret: Qrxv4BgkI6sAYNpG7rX5IHWVc5mKoG # accessKeySecret
    domain: dysmsapi.aliyuncs.com # 固定不变
    regionId: cn-hangzhou # 固定不变
    templateCode: SMS_205882311 # 你的模板code
    signName: 东软教育 # 你的签名

